# Generated by Django 6.0.1 on 2026-01-26 04:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_stripe_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Сумма оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_status",
            field=models.CharField(blank=True, null=True),
        ),
    ]
