# Generated by Django 6.0.1 on 2026-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_amount_alter_payment_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
